export default {
  contacts: {
    list: {
      1: {
        id: 1,
        firstName: 'Tracy',
        lastName: 'McCullough',
        phone: '+38 (099) 999-99-99',
        birthDate: '1986-11-20',
        email: 'Tracy82@hotmail.com',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/praveen_vijaya/128.jpg',
        position: 1,
      },
      2: {
        id: 2,
        firstName: 'Jensen',
        lastName: 'Beer',
        phone: '+38 (099) 222222222',
        birthDate: '1973-3-1',
        email: 'Jensen_Beer40@gmail.com',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/sementiy/128.jpg',
        position: 0,
      },
      3: {
        id: 3,
        firstName: 'Adele',
        lastName: 'Parker',
        phone: '+38 (099) 222222222',
        birthDate: '1977-4-28',
        email: 'Adele11@yahoo.com',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/woodsman001/128.jpg',
        position: 3,
      },
      4: {
        id: 4,
        firstName: 'Leon',
        lastName: 'Brakus',
        phone: '+38 (099) 222222222',
        birthDate: '1986-3-13',
        email: 'Leilani_Lang98@hotmail.com',
        image: 'https://s3.amazonaws.com/uifaces/faces/twitter/shoaib253/128.jpg',
        position: 2,
      },
    },
    pending: false,
  },
};
